import os
from pathlib import Path
from docx import Document
from docx.shared import Inches

def main():
    doc = Document()
    doc.add_heading('Preprocessing Pipeline - Sample Outputs', 0)
    
    doc.add_paragraph(
        "This document contains sample before/after comparison panels generated by the "
        "DIP preprocessing pipeline (preprocess_intensity_spatial.py)."
    )
    
    doc.add_heading('Pipeline Steps Applied:', level=2)
    doc.add_paragraph("1. Median filter (k=3) for noise removal")
    doc.add_paragraph("2. CLAHE (clip=2.0, tile=8x8) on LAB color space for contrast enhancement")
    doc.add_paragraph("3. Unsharp mask (radius=1, amount=1.5) for edge recovery")
    doc.add_paragraph("4. Resize and pad to 224x224 (preserves aspect ratio)")
    
    doc.add_heading('Sample Comparisons', level=2)
    
    base_dir = Path(r"c:\Users\Harish Raghul T\Desktop\Smart Agri-tool\data\preprocessed")
    
    # We will pick a few samples from different diseases
    diseases = ["rust", "blight", "powdery_mildew"]
    
    samples_added = 0
    for disease in diseases:
        demo_dir = base_dir / disease / "_demo_panels" / "train"
        if demo_dir.exists():
            for class_dir in demo_dir.iterdir():
                if class_dir.is_dir():
                    images = list(class_dir.glob("*.jpg"))
                    if images:
                        img_path = images[0] # Pick the first image from this class
                        doc.add_heading(f'Disease: {disease} | Class: {class_dir.name}', level=3)
                        doc.add_picture(str(img_path), width=Inches(6.0))
                        samples_added += 1
                        if samples_added >= 4:
                            break
        if samples_added >= 4:
            break
            
    doc_path = r"c:\Users\Harish Raghul T\Desktop\Smart Agri-tool\Preprocessing_Samples.docx"
    doc.save(doc_path)
    print(f"Document saved to: {doc_path}")

if __name__ == "__main__":
    main()
